# Generated by Django 5.0.6 on 2026-08-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('motion', 'Motion'), ('cry', 'Cry')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='babies.baby')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
