services:
  - type: web
    name: babycare-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT babycare_backend.asgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: babycare-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: babycare-redis
          property: connectionString

  - type: redis
    name: babycare-redis
    plan: free
    ipAllowList: []

databases:
  - name: babycare-db
    plan: free
